### ISSUE TITLE
Change to JavaScript and Ajax, instead of PHP output.

### ISSUE THREAD

**Issue by AKKamath** [AdityaK-sophos/Competitive-Application#1]
Currently the main file includes each scraping file then takes the output of that file. It would be more practical and efficient to instead have the main file use JavaScript and Ajax, and request the data from the PHP file.

**Comment by mdownie** [comment]
I wouldn't mind taking care of this if it is still available.

**Comment by AKKamath** [comment]
Go for it

**Comment by markszymik** [comment]
Can I have it too please?

**Comment by AKKamath** [comment]
Feel free to try it out
